#!/bin/sh

ng lint --format codeFrame
EXIT_CODE=$?
if [[ ${EXIT_CODE} -ne 0 ]]; then
    exit 1
else
	echo "Lint completed successfully\n"
fi

#ng test --singleRun
#EXIT_CODE=$?
#if [[ ${EXIT_CODE} -ne 0 ]]; then
#    exit 1
#else
#	echo "Tests passed\n"
#fi

ng build --target=production --aot
EXIT_CODE=$?
if [[ ${EXIT_CODE} -ne 0 ]]; then
    exit 1
else
	echo "Build completed successfully\n"
fi

exit 0
